/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Bottle extends Portable {
  private long swigCPtr;

  protected Bottle(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.SWIGBottleUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Bottle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_Bottle(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public boolean check(String key, String comment) {
    return yarpJNI.Bottle_check__SWIG_0_0(swigCPtr, this, key, comment);
  }

  public Value check(String key, Value fallback, String comment) {
    return new Value(yarpJNI.Bottle_check__SWIG_0_1(swigCPtr, this, key, Value.getCPtr(fallback), fallback, comment), true);
  }

  public Value check(String key, Value fallback) {
    return new Value(yarpJNI.Bottle_check__SWIG_0_2(swigCPtr, this, key, Value.getCPtr(fallback), fallback), true);
  }

  public Bottle findGroup(String key, String comment) {
    return new Bottle(yarpJNI.Bottle_findGroup__SWIG_0_0(swigCPtr, this, key, comment), false);
  }

  public Bottle() {
    this(yarpJNI.new_Bottle__SWIG_0(), true);
  }

  public Bottle(String text) {
    this(yarpJNI.new_Bottle__SWIG_1(text), true);
  }

  public Bottle(Bottle bottle) {
    this(yarpJNI.new_Bottle__SWIG_2(Bottle.getCPtr(bottle), bottle), true);
  }

  public void clear() {
    yarpJNI.Bottle_clear(swigCPtr, this);
  }

  public void addInt(int x) {
    yarpJNI.Bottle_addInt(swigCPtr, this, x);
  }

  public void addVocab(int x) {
    yarpJNI.Bottle_addVocab(swigCPtr, this, x);
  }

  public void addDouble(double x) {
    yarpJNI.Bottle_addDouble(swigCPtr, this, x);
  }

  public void addString(String str) {
    yarpJNI.Bottle_addString(swigCPtr, this, str);
  }

  public void add(Value value) {
    yarpJNI.Bottle_add(swigCPtr, this, Value.getCPtr(value), value);
  }

  public Bottle addList() {
    return new Bottle(yarpJNI.Bottle_addList(swigCPtr, this), false);
  }

  public Value pop() {
    return new Value(yarpJNI.Bottle_pop(swigCPtr, this), false);
  }

  public Value get(int index) {
    return new Value(yarpJNI.Bottle_get(swigCPtr, this, index), false);
  }

  public int size() {
    return yarpJNI.Bottle_size(swigCPtr, this);
  }

  public void fromString(String text) {
    yarpJNI.Bottle_fromString(swigCPtr, this, text);
  }

  public void fromBinary(String buf, int len) {
    yarpJNI.Bottle_fromBinary(swigCPtr, this, buf, len);
  }

  public String toBinary(SWIGTYPE_p_int size) {
    return yarpJNI.Bottle_toBinary__SWIG_0(swigCPtr, this, SWIGTYPE_p_int.getCPtr(size));
  }

  public String toBinary() {
    return yarpJNI.Bottle_toBinary__SWIG_1(swigCPtr, this);
  }

  public ConstString toString_c() {
    return new ConstString(yarpJNI.Bottle_toString_c(swigCPtr, this), true);
  }

  public boolean write(ConnectionWriter writer) {
    return yarpJNI.Bottle_write(swigCPtr, this, ConnectionWriter.getCPtr(writer), writer);
  }

  public void onCommencement() {
    yarpJNI.Bottle_onCommencement(swigCPtr, this);
  }

  public boolean check(String key) {
    return yarpJNI.Bottle_check__SWIG_1(swigCPtr, this, key);
  }

  public Value find(String key) {
    return new Value(yarpJNI.Bottle_find(swigCPtr, this, key), false);
  }

  public Bottle findGroup(String key) {
    return new Bottle(yarpJNI.Bottle_findGroup__SWIG_1(swigCPtr, this, key), false);
  }

  public void copy(Bottle alt, int first, int len) {
    yarpJNI.Bottle_copy__SWIG_0(swigCPtr, this, Bottle.getCPtr(alt), alt, first, len);
  }

  public void copy(Bottle alt, int first) {
    yarpJNI.Bottle_copy__SWIG_1(swigCPtr, this, Bottle.getCPtr(alt), alt, first);
  }

  public void copy(Bottle alt) {
    yarpJNI.Bottle_copy__SWIG_2(swigCPtr, this, Bottle.getCPtr(alt), alt);
  }

  public static Bottle getNullBottle() {
    return new Bottle(yarpJNI.Bottle_getNullBottle(), false);
  }

  public boolean isEqual(Bottle alt) {
    return yarpJNI.Bottle_isEqual(swigCPtr, this, Bottle.getCPtr(alt), alt);
  }

  public boolean notEqual(Bottle alt) {
    return yarpJNI.Bottle_notEqual(swigCPtr, this, Bottle.getCPtr(alt), alt);
  }

  public void append(Bottle alt) {
    yarpJNI.Bottle_append(swigCPtr, this, Bottle.getCPtr(alt), alt);
  }

  public Bottle tail() {
    return new Bottle(yarpJNI.Bottle_tail(swigCPtr, this), true);
  }

  public void specialize(int subCode) {
    yarpJNI.Bottle_specialize(swigCPtr, this, subCode);
  }

  public int getSpecialization() {
    return yarpJNI.Bottle_getSpecialization(swigCPtr, this);
  }

  public void setNested(boolean nested) {
    yarpJNI.Bottle_setNested(swigCPtr, this, nested);
  }

  public String toString() {
    return yarpJNI.Bottle_toString(swigCPtr, this);
  }

}
