/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class BufferedPortImageRgb extends Contactable {
  private long swigCPtr;

  protected BufferedPortImageRgb(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.SWIGBufferedPortImageRgbUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BufferedPortImageRgb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_BufferedPortImageRgb(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public BufferedPortImageRgb() {
    this(yarpJNI.new_BufferedPortImageRgb(), true);
  }

  public boolean addOutput(String name) {
    return yarpJNI.BufferedPortImageRgb_addOutput__SWIG_0(swigCPtr, this, name);
  }

  public boolean addOutput(String name, String carrier) {
    return yarpJNI.BufferedPortImageRgb_addOutput__SWIG_1(swigCPtr, this, name, carrier);
  }

  public boolean addOutput(Contact contact) {
    return yarpJNI.BufferedPortImageRgb_addOutput__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public void close() {
    yarpJNI.BufferedPortImageRgb_close(swigCPtr, this);
  }

  public void interrupt() {
    yarpJNI.BufferedPortImageRgb_interrupt(swigCPtr, this);
  }

  public int getPendingReads() {
    return yarpJNI.BufferedPortImageRgb_getPendingReads(swigCPtr, this);
  }

  public Contact where() {
    return new Contact(yarpJNI.BufferedPortImageRgb_where(swigCPtr, this), true);
  }

  public ConstString getName() {
    return new ConstString(yarpJNI.BufferedPortImageRgb_getName(swigCPtr, this), true);
  }

  public ImageRgb prepare() {
    return new ImageRgb(yarpJNI.BufferedPortImageRgb_prepare(swigCPtr, this), false);
  }

  public void write(boolean forceStrict) {
    yarpJNI.BufferedPortImageRgb_write__SWIG_0(swigCPtr, this, forceStrict);
  }

  public void write() {
    yarpJNI.BufferedPortImageRgb_write__SWIG_1(swigCPtr, this);
  }

  public void writeStrict() {
    yarpJNI.BufferedPortImageRgb_writeStrict(swigCPtr, this);
  }

  public void setStrict(boolean strict) {
    yarpJNI.BufferedPortImageRgb_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.BufferedPortImageRgb_setStrict__SWIG_1(swigCPtr, this);
  }

  public ImageRgb read(boolean shouldWait) {
    long cPtr = yarpJNI.BufferedPortImageRgb_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public ImageRgb read() {
    long cPtr = yarpJNI.BufferedPortImageRgb_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public ImageRgb lastRead() {
    long cPtr = yarpJNI.BufferedPortImageRgb_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.BufferedPortImageRgb_isClosed(swigCPtr, this);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.BufferedPortImageRgb_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void onRead(ImageRgb datum) {
    yarpJNI.BufferedPortImageRgb_onRead(swigCPtr, this, ImageRgb.getCPtr(datum), datum);
  }

  public void useCallback(TypedReaderCallbackImageRgb callback) {
    yarpJNI.BufferedPortImageRgb_useCallback__SWIG_0(swigCPtr, this, TypedReaderCallbackImageRgb.getCPtr(callback), callback);
  }

  public void useCallback() {
    yarpJNI.BufferedPortImageRgb_useCallback__SWIG_1(swigCPtr, this);
  }

  public boolean setEnvelope(PortWriter envelope) {
    return yarpJNI.BufferedPortImageRgb_setEnvelope(swigCPtr, this, PortWriter.getCPtr(envelope), envelope);
  }

  public boolean getEnvelope(PortReader envelope) {
    return yarpJNI.BufferedPortImageRgb_getEnvelope(swigCPtr, this, PortReader.getCPtr(envelope), envelope);
  }

  public int getInputCount() {
    return yarpJNI.BufferedPortImageRgb_getInputCount(swigCPtr, this);
  }

  public int getOutputCount() {
    return yarpJNI.BufferedPortImageRgb_getOutputCount(swigCPtr, this);
  }

  public void getReport(PortReport reporter) {
    yarpJNI.BufferedPortImageRgb_getReport(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public void setReporter(PortReport reporter) {
    yarpJNI.BufferedPortImageRgb_setReporter(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.BufferedPortImageRgb_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.BufferedPortImageRgb_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

}
