/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ConnectionWriter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConnectionWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConnectionWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_ConnectionWriter(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void appendBlock(String data, int len) {
    yarpJNI.ConnectionWriter_appendBlock(swigCPtr, this, data, len);
  }

  public void appendInt(int data) {
    yarpJNI.ConnectionWriter_appendInt(swigCPtr, this, data);
  }

  public void appendDouble(double data) {
    yarpJNI.ConnectionWriter_appendDouble(swigCPtr, this, data);
  }

  public void appendString(String str, int terminate) {
    yarpJNI.ConnectionWriter_appendString__SWIG_0(swigCPtr, this, str, terminate);
  }

  public void appendString(String str) {
    yarpJNI.ConnectionWriter_appendString__SWIG_1(swigCPtr, this, str);
  }

  public void appendExternalBlock(String data, int len) {
    yarpJNI.ConnectionWriter_appendExternalBlock(swigCPtr, this, data, len);
  }

  public boolean isTextMode() {
    return yarpJNI.ConnectionWriter_isTextMode(swigCPtr, this);
  }

  public void declareSizes(int argc, SWIGTYPE_p_int argv) {
    yarpJNI.ConnectionWriter_declareSizes(swigCPtr, this, argc, SWIGTYPE_p_int.getCPtr(argv));
  }

  public void setReplyHandler(PortReader reader) {
    yarpJNI.ConnectionWriter_setReplyHandler(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setReference(Portable obj) {
    yarpJNI.ConnectionWriter_setReference(swigCPtr, this, Portable.getCPtr(obj), obj);
  }

  public boolean convertTextMode() {
    return yarpJNI.ConnectionWriter_convertTextMode(swigCPtr, this);
  }

  public boolean isValid() {
    return yarpJNI.ConnectionWriter_isValid(swigCPtr, this);
  }

  public boolean isActive() {
    return yarpJNI.ConnectionWriter_isActive(swigCPtr, this);
  }

  public boolean isError() {
    return yarpJNI.ConnectionWriter_isError(swigCPtr, this);
  }

}
