/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ConnectionReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConnectionReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConnectionReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_ConnectionReader(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean expectBlock(String data, int len) {
    return yarpJNI.ConnectionReader_expectBlock(swigCPtr, this, data, len);
  }

  public ConstString expectText(int terminatingChar) {
    return new ConstString(yarpJNI.ConnectionReader_expectText__SWIG_0(swigCPtr, this, terminatingChar), true);
  }

  public ConstString expectText() {
    return new ConstString(yarpJNI.ConnectionReader_expectText__SWIG_1(swigCPtr, this), true);
  }

  public int expectInt() {
    return yarpJNI.ConnectionReader_expectInt(swigCPtr, this);
  }

  public double expectDouble() {
    return yarpJNI.ConnectionReader_expectDouble(swigCPtr, this);
  }

  public boolean isTextMode() {
    return yarpJNI.ConnectionReader_isTextMode(swigCPtr, this);
  }

  public boolean convertTextMode() {
    return yarpJNI.ConnectionReader_convertTextMode(swigCPtr, this);
  }

  public int getSize() {
    return yarpJNI.ConnectionReader_getSize(swigCPtr, this);
  }

  public ConnectionWriter getWriter() {
    long cPtr = yarpJNI.ConnectionReader_getWriter(swigCPtr, this);
    return (cPtr == 0) ? null : new ConnectionWriter(cPtr, false);
  }

  public Portable getReference() {
    long cPtr = yarpJNI.ConnectionReader_getReference(swigCPtr, this);
    return (cPtr == 0) ? null : new Portable(cPtr, false);
  }

  public Contact getRemoteContact() {
    return new Contact(yarpJNI.ConnectionReader_getRemoteContact(swigCPtr, this), true);
  }

  public Contact getLocalContact() {
    return new Contact(yarpJNI.ConnectionReader_getLocalContact(swigCPtr, this), true);
  }

  public boolean isValid() {
    return yarpJNI.ConnectionReader_isValid(swigCPtr, this);
  }

  public boolean isActive() {
    return yarpJNI.ConnectionReader_isActive(swigCPtr, this);
  }

  public boolean isError() {
    return yarpJNI.ConnectionReader_isError(swigCPtr, this);
  }

}
