/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ConstString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConstString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConstString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_ConstString(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ConstString() {
    this(yarpJNI.new_ConstString__SWIG_0(), true);
  }

  public ConstString(String str) {
    this(yarpJNI.new_ConstString__SWIG_1(str), true);
  }

  public ConstString(ConstString alt) {
    this(yarpJNI.new_ConstString__SWIG_2(ConstString.getCPtr(alt), alt), true);
  }

  public String c_str() {
    return yarpJNI.ConstString_c_str(swigCPtr, this);
  }

  public String toString() {
    return yarpJNI.ConstString_toString(swigCPtr, this);
  }

  public boolean isEqual(ConstString alt) {
    return yarpJNI.ConstString_isEqual__SWIG_0(swigCPtr, this, ConstString.getCPtr(alt), alt);
  }

  public boolean notEqual(ConstString alt) {
    return yarpJNI.ConstString_notEqual__SWIG_0(swigCPtr, this, ConstString.getCPtr(alt), alt);
  }

  public boolean isEqual(String str) {
    return yarpJNI.ConstString_isEqual__SWIG_1(swigCPtr, this, str);
  }

  public boolean notEqual(String str) {
    return yarpJNI.ConstString_notEqual__SWIG_1(swigCPtr, this, str);
  }

  public int length() {
    return yarpJNI.ConstString_length(swigCPtr, this);
  }

}
