/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Contactable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Contactable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Contactable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_Contactable(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean open() {
    return yarpJNI.Contactable_open__SWIG_0(swigCPtr, this);
  }

  public boolean open(String name) {
    return yarpJNI.Contactable_open__SWIG_1(swigCPtr, this, name);
  }

  public boolean open(Contact contact, boolean registerName) {
    return yarpJNI.Contactable_open__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact, registerName);
  }

  public boolean open(Contact contact) {
    return yarpJNI.Contactable_open__SWIG_3(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public boolean addOutput(String name) {
    return yarpJNI.Contactable_addOutput__SWIG_0(swigCPtr, this, name);
  }

  public boolean addOutput(String name, String carrier) {
    return yarpJNI.Contactable_addOutput__SWIG_1(swigCPtr, this, name, carrier);
  }

  public boolean addOutput(Contact contact) {
    return yarpJNI.Contactable_addOutput__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public void close() {
    yarpJNI.Contactable_close(swigCPtr, this);
  }

  public void interrupt() {
    yarpJNI.Contactable_interrupt(swigCPtr, this);
  }

  public Contact where() {
    return new Contact(yarpJNI.Contactable_where(swigCPtr, this), true);
  }

  public ConstString getName() {
    return new ConstString(yarpJNI.Contactable_getName(swigCPtr, this), true);
  }

  public boolean setEnvelope(PortWriter envelope) {
    return yarpJNI.Contactable_setEnvelope(swigCPtr, this, PortWriter.getCPtr(envelope), envelope);
  }

  public boolean getEnvelope(PortReader envelope) {
    return yarpJNI.Contactable_getEnvelope(swigCPtr, this, PortReader.getCPtr(envelope), envelope);
  }

  public int getInputCount() {
    return yarpJNI.Contactable_getInputCount(swigCPtr, this);
  }

  public int getOutputCount() {
    return yarpJNI.Contactable_getOutputCount(swigCPtr, this);
  }

  public void getReport(PortReport reporter) {
    yarpJNI.Contactable_getReport(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public void setReporter(PortReport reporter) {
    yarpJNI.Contactable_setReporter(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

}
