/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class FlexImage extends Image {
  private long swigCPtr;

  protected FlexImage(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.SWIGFlexImageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FlexImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_FlexImage(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void setPixelCode(int imgPixelCode) {
    yarpJNI.FlexImage_setPixelCode(swigCPtr, this, imgPixelCode);
  }

  public void setPixelSize(int imgPixelSize) {
    yarpJNI.FlexImage_setPixelSize(swigCPtr, this, imgPixelSize);
  }

  public void setQuantum(int imgQuantum) {
    yarpJNI.FlexImage_setQuantum(swigCPtr, this, imgQuantum);
  }

  public FlexImage() {
    this(yarpJNI.new_FlexImage(), true);
  }

}
