/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IAmplifierControlRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IAmplifierControlRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAmplifierControlRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IAmplifierControlRaw(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean enableAmpRaw(int j) {
    return yarpJNI.IAmplifierControlRaw_enableAmpRaw(swigCPtr, this, j);
  }

  public boolean disableAmpRaw(int j) {
    return yarpJNI.IAmplifierControlRaw_disableAmpRaw(swigCPtr, this, j);
  }

  public boolean getCurrentsRaw(SWIGTYPE_p_double vals) {
    return yarpJNI.IAmplifierControlRaw_getCurrentsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(vals));
  }

  public boolean getCurrentRaw(int j, SWIGTYPE_p_double val) {
    return yarpJNI.IAmplifierControlRaw_getCurrentRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(val));
  }

  public boolean setMaxCurrentRaw(int j, double v) {
    return yarpJNI.IAmplifierControlRaw_setMaxCurrentRaw(swigCPtr, this, j, v);
  }

  public boolean getAmpStatusRaw(SWIGTYPE_p_int st) {
    return yarpJNI.IAmplifierControlRaw_getAmpStatusRaw(swigCPtr, this, SWIGTYPE_p_int.getCPtr(st));
  }

}
