/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IControlCalibrationRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IControlCalibrationRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IControlCalibrationRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IControlCalibrationRaw(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean calibrateRaw(int j, double p) {
    return yarpJNI.IControlCalibrationRaw_calibrateRaw(swigCPtr, this, j, p);
  }

  public boolean doneRaw(int j) {
    return yarpJNI.IControlCalibrationRaw_doneRaw(swigCPtr, this, j);
  }

}
