/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IControlDebug {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IControlDebug(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IControlDebug obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IControlDebug(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean setPrintFunction(SWIGTYPE_p_f_p_q_const__char_v_______int f) {
    return yarpJNI.IControlDebug_setPrintFunction(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_v_______int.getCPtr(f));
  }

  public boolean loadBootMemory() {
    return yarpJNI.IControlDebug_loadBootMemory(swigCPtr, this);
  }

  public boolean saveBootMemory() {
    return yarpJNI.IControlDebug_saveBootMemory(swigCPtr, this);
  }

}
