/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IConfig(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean open(Searchable config) {
    return yarpJNI.IConfig_open(swigCPtr, this, Searchable.getCPtr(config), config);
  }

  public boolean close() {
    return yarpJNI.IConfig_close(swigCPtr, this);
  }

  public boolean configure(Searchable config) {
    return yarpJNI.IConfig_configure(swigCPtr, this, Searchable.getCPtr(config), config);
  }

  public IConfig() {
    this(yarpJNI.new_IConfig(), true);
  }

}
