/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IControlCalibration2Raw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IControlCalibration2Raw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IControlCalibration2Raw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IControlCalibration2Raw(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean calibrate2Raw(int axis, long type, double p1, double p2, double p3) {
    return yarpJNI.IControlCalibration2Raw_calibrate2Raw(swigCPtr, this, axis, type, p1, p2, p3);
  }

  public boolean doneRaw(int j) {
    return yarpJNI.IControlCalibration2Raw_doneRaw(swigCPtr, this, j);
  }

}
