/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IControlLimitsRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IControlLimitsRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IControlLimitsRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IControlLimitsRaw(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean setLimitsRaw(int axis, double min, double max) {
    return yarpJNI.IControlLimitsRaw_setLimitsRaw(swigCPtr, this, axis, min, max);
  }

  public boolean getLimitsRaw(int axis, SWIGTYPE_p_double min, SWIGTYPE_p_double max) {
    return yarpJNI.IControlLimitsRaw_getLimitsRaw(swigCPtr, this, axis, SWIGTYPE_p_double.getCPtr(min), SWIGTYPE_p_double.getCPtr(max));
  }

}
