/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IEncoders {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IEncoders(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IEncoders obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IEncoders(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean getAxes(SWIGTYPE_p_int ax) {
    return yarpJNI.IEncoders_getAxes__SWIG_0(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ax));
  }

  public boolean resetEncoder(int j) {
    return yarpJNI.IEncoders_resetEncoder(swigCPtr, this, j);
  }

  public boolean resetEncoders() {
    return yarpJNI.IEncoders_resetEncoders(swigCPtr, this);
  }

  public boolean setEncoder(int j, double val) {
    return yarpJNI.IEncoders_setEncoder(swigCPtr, this, j, val);
  }

  public boolean setEncoders(SWIGTYPE_p_double vals) {
    return yarpJNI.IEncoders_setEncoders__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(vals));
  }

  public boolean getEncoder(int j, SWIGTYPE_p_double v) {
    return yarpJNI.IEncoders_getEncoder__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(v));
  }

  public boolean getEncoders(SWIGTYPE_p_double encs) {
    return yarpJNI.IEncoders_getEncoders__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(encs));
  }

  public boolean getEncoderSpeed(int j, SWIGTYPE_p_double sp) {
    return yarpJNI.IEncoders_getEncoderSpeed__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(sp));
  }

  public boolean getEncoderSpeeds(SWIGTYPE_p_double spds) {
    return yarpJNI.IEncoders_getEncoderSpeeds__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAcceleration(int j, SWIGTYPE_p_double spds) {
    return yarpJNI.IEncoders_getEncoderAcceleration__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAccelerations(SWIGTYPE_p_double accs) {
    return yarpJNI.IEncoders_getEncoderAccelerations__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

  public int getAxes() {
    return yarpJNI.IEncoders_getAxes__SWIG_1(swigCPtr, this);
  }

  public boolean setEncoders(DVector data) {
    return yarpJNI.IEncoders_setEncoders__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public double getEncoder(int j) {
    return yarpJNI.IEncoders_getEncoder__SWIG_1(swigCPtr, this, j);
  }

  public boolean getEncoders(DVector data) {
    return yarpJNI.IEncoders_getEncoders__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public double getEncoderSpeed(int j) {
    return yarpJNI.IEncoders_getEncoderSpeed__SWIG_1(swigCPtr, this, j);
  }

  public boolean getEncoderSpeeds(DVector data) {
    return yarpJNI.IEncoders_getEncoderSpeeds__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public double getEncoderAcceleration(int j) {
    return yarpJNI.IEncoders_getEncoderAcceleration__SWIG_1(swigCPtr, this, j);
  }

  public boolean getEncoderAccelerations(DVector data) {
    return yarpJNI.IEncoders_getEncoderAccelerations__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

}
