/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IEncodersRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IEncodersRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IEncodersRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IEncodersRaw(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean getAxes(SWIGTYPE_p_int ax) {
    return yarpJNI.IEncodersRaw_getAxes(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ax));
  }

  public boolean resetEncoderRaw(int j) {
    return yarpJNI.IEncodersRaw_resetEncoderRaw(swigCPtr, this, j);
  }

  public boolean resetEncodersRaw() {
    return yarpJNI.IEncodersRaw_resetEncodersRaw(swigCPtr, this);
  }

  public boolean setEncoderRaw(int j, double val) {
    return yarpJNI.IEncodersRaw_setEncoderRaw(swigCPtr, this, j, val);
  }

  public boolean setEncodersRaw(SWIGTYPE_p_double vals) {
    return yarpJNI.IEncodersRaw_setEncodersRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(vals));
  }

  public boolean getEncoderRaw(int j, SWIGTYPE_p_double v) {
    return yarpJNI.IEncodersRaw_getEncoderRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(v));
  }

  public boolean getEncodersRaw(SWIGTYPE_p_double encs) {
    return yarpJNI.IEncodersRaw_getEncodersRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(encs));
  }

  public boolean getEncoderSpeedRaw(int j, SWIGTYPE_p_double sp) {
    return yarpJNI.IEncodersRaw_getEncoderSpeedRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(sp));
  }

  public boolean getEncoderSpeedsRaw(SWIGTYPE_p_double spds) {
    return yarpJNI.IEncodersRaw_getEncoderSpeedsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAccelerationRaw(int j, SWIGTYPE_p_double spds) {
    return yarpJNI.IEncodersRaw_getEncoderAccelerationRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAccelerationsRaw(SWIGTYPE_p_double accs) {
    return yarpJNI.IEncodersRaw_getEncoderAccelerationsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

}
