/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IFrameGrabberImage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IFrameGrabberImage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IFrameGrabberImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IFrameGrabberImage(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean getImage(ImageRgb image) {
    return yarpJNI.IFrameGrabberImage_getImage(swigCPtr, this, ImageRgb.getCPtr(image), image);
  }

  public int height() {
    return yarpJNI.IFrameGrabberImage_height(swigCPtr, this);
  }

  public int width() {
    return yarpJNI.IFrameGrabberImage_width(swigCPtr, this);
  }

}
