/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ImageFloat extends Image {
  private long swigCPtr;

  protected ImageFloat(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.SWIGImageFloatUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_ImageFloat(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public int getPixelSize() {
    return yarpJNI.ImageFloat_getPixelSize(swigCPtr, this);
  }

  public int getPixelCode() {
    return yarpJNI.ImageFloat_getPixelCode(swigCPtr, this);
  }

  public SWIGTYPE_p_float pixel(int x, int y) {
    return new SWIGTYPE_p_float(yarpJNI.ImageFloat_pixel(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_float access(int x, int y) {
    return new SWIGTYPE_p_float(yarpJNI.ImageFloat_access(swigCPtr, this, x, y), false);
  }

  public SWIGTYPE_p_float safePixel(int x, int y) {
    return new SWIGTYPE_p_float(yarpJNI.ImageFloat_safePixel(swigCPtr, this, x, y), false);
  }

  public float getPixel(int x, int y) {
    return yarpJNI.ImageFloat_getPixel(swigCPtr, this, x, y);
  }

  public void setPixel(int x, int y, float v) {
    yarpJNI.ImageFloat_setPixel(swigCPtr, this, x, y, v);
  }

  public ImageFloat() {
    this(yarpJNI.new_ImageFloat(), true);
  }

}
