/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IPidControl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IPidControl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPidControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IPidControl(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean setPids(SWIGTYPE_p_Pid pids) {
    return yarpJNI.IPidControl_setPids__SWIG_0(swigCPtr, this, SWIGTYPE_p_Pid.getCPtr(pids));
  }

  public boolean setReference(int j, double ref) {
    return yarpJNI.IPidControl_setReference(swigCPtr, this, j, ref);
  }

  public boolean setReferences(SWIGTYPE_p_double refs) {
    return yarpJNI.IPidControl_setReferences__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(refs));
  }

  public boolean setErrorLimit(int j, double limit) {
    return yarpJNI.IPidControl_setErrorLimit(swigCPtr, this, j, limit);
  }

  public boolean setErrorLimits(SWIGTYPE_p_double limits) {
    return yarpJNI.IPidControl_setErrorLimits__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(limits));
  }

  public boolean getError(int j, SWIGTYPE_p_double err) {
    return yarpJNI.IPidControl_getError__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(err));
  }

  public boolean getErrors(SWIGTYPE_p_double errs) {
    return yarpJNI.IPidControl_getErrors__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(errs));
  }

  public boolean getOutput(int j, SWIGTYPE_p_double out) {
    return yarpJNI.IPidControl_getOutput__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(out));
  }

  public boolean getOutputs(SWIGTYPE_p_double outs) {
    return yarpJNI.IPidControl_getOutputs__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(outs));
  }

  public boolean getPids(SWIGTYPE_p_Pid pids) {
    return yarpJNI.IPidControl_getPids__SWIG_0(swigCPtr, this, SWIGTYPE_p_Pid.getCPtr(pids));
  }

  public boolean getReference(int j, SWIGTYPE_p_double ref) {
    return yarpJNI.IPidControl_getReference__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(ref));
  }

  public boolean getReferences(SWIGTYPE_p_double refs) {
    return yarpJNI.IPidControl_getReferences__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(refs));
  }

  public boolean getErrorLimit(int j, SWIGTYPE_p_double limit) {
    return yarpJNI.IPidControl_getErrorLimit__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(limit));
  }

  public boolean getErrorLimits(SWIGTYPE_p_double limits) {
    return yarpJNI.IPidControl_getErrorLimits__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(limits));
  }

  public boolean resetPid(int j) {
    return yarpJNI.IPidControl_resetPid(swigCPtr, this, j);
  }

  public boolean disablePid(int j) {
    return yarpJNI.IPidControl_disablePid(swigCPtr, this, j);
  }

  public boolean enablePid(int j) {
    return yarpJNI.IPidControl_enablePid(swigCPtr, this, j);
  }

  public boolean setOffset(int j, double v) {
    return yarpJNI.IPidControl_setOffset(swigCPtr, this, j, v);
  }

  public boolean setReferences(DVector data) {
    return yarpJNI.IPidControl_setReferences__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean getReference(int j, DVector data) {
    return yarpJNI.IPidControl_getReference__SWIG_1(swigCPtr, this, j, DVector.getCPtr(data), data);
  }

  public boolean getReferences(DVector data) {
    return yarpJNI.IPidControl_getReferences__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean setErrorLimits(DVector data) {
    return yarpJNI.IPidControl_setErrorLimits__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean getErrorLimit(int j, DVector data) {
    return yarpJNI.IPidControl_getErrorLimit__SWIG_1(swigCPtr, this, j, DVector.getCPtr(data), data);
  }

  public boolean getErrorLimits(DVector data) {
    return yarpJNI.IPidControl_getErrorLimits__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean getError(int j, DVector data) {
    return yarpJNI.IPidControl_getError__SWIG_1(swigCPtr, this, j, DVector.getCPtr(data), data);
  }

  public boolean getErrors(DVector data) {
    return yarpJNI.IPidControl_getErrors__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean getOutput(int j, DVector data) {
    return yarpJNI.IPidControl_getOutput__SWIG_1(swigCPtr, this, j, DVector.getCPtr(data), data);
  }

  public boolean getOutputs(DVector data) {
    return yarpJNI.IPidControl_getOutputs__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean setPid(int j, Pid pid) {
    return yarpJNI.IPidControl_setPid(swigCPtr, this, j, Pid.getCPtr(pid), pid);
  }

  public boolean setPids(PidVector pids) {
    return yarpJNI.IPidControl_setPids__SWIG_1(swigCPtr, this, PidVector.getCPtr(pids), pids);
  }

  public boolean getPid(int j, PidVector pid) {
    return yarpJNI.IPidControl_getPid(swigCPtr, this, j, PidVector.getCPtr(pid), pid);
  }

  public boolean getPids(PidVector pids) {
    return yarpJNI.IPidControl_getPids__SWIG_1(swigCPtr, this, PidVector.getCPtr(pids), pids);
  }

}
