/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ITorqueControlRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITorqueControlRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITorqueControlRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_ITorqueControlRaw(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean getAxes(SWIGTYPE_p_int ax) {
    return yarpJNI.ITorqueControlRaw_getAxes(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ax));
  }

  public boolean setTorqueMode() {
    return yarpJNI.ITorqueControlRaw_setTorqueMode(swigCPtr, this);
  }

  public double getRefTorqueRaw(int j) {
    return yarpJNI.ITorqueControlRaw_getRefTorqueRaw(swigCPtr, this, j);
  }

  public void getRefTorquesRaw(SWIGTYPE_p_double t) {
    yarpJNI.ITorqueControlRaw_getRefTorquesRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean setTorquesRaw(SWIGTYPE_p_double t) {
    return yarpJNI.ITorqueControlRaw_setTorquesRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public void setTorqueRaw(int j, double t) {
    yarpJNI.ITorqueControlRaw_setTorqueRaw(swigCPtr, this, j, t);
  }

}
