/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IVelocityControlRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IVelocityControlRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVelocityControlRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IVelocityControlRaw(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean getAxes(SWIGTYPE_p_int axis) {
    return yarpJNI.IVelocityControlRaw_getAxes(swigCPtr, this, SWIGTYPE_p_int.getCPtr(axis));
  }

  public boolean setVelocityMode() {
    return yarpJNI.IVelocityControlRaw_setVelocityMode(swigCPtr, this);
  }

  public boolean velocityMoveRaw(int j, double sp) {
    return yarpJNI.IVelocityControlRaw_velocityMoveRaw__SWIG_0(swigCPtr, this, j, sp);
  }

  public boolean velocityMoveRaw(SWIGTYPE_p_double sp) {
    return yarpJNI.IVelocityControlRaw_velocityMoveRaw__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(sp));
  }

  public boolean setRefAccelerationRaw(int j, double acc) {
    return yarpJNI.IVelocityControlRaw_setRefAccelerationRaw(swigCPtr, this, j, acc);
  }

  public boolean setRefAccelerationsRaw(SWIGTYPE_p_double accs) {
    return yarpJNI.IVelocityControlRaw_setRefAccelerationsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

  public boolean getRefAccelerationRaw(int j, SWIGTYPE_p_double acc) {
    return yarpJNI.IVelocityControlRaw_getRefAccelerationRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(acc));
  }

  public boolean getRefAccelerationsRaw(SWIGTYPE_p_double accs) {
    return yarpJNI.IVelocityControlRaw_getRefAccelerationsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

  public boolean stopRaw(int j) {
    return yarpJNI.IVelocityControlRaw_stopRaw__SWIG_0(swigCPtr, this, j);
  }

  public boolean stopRaw() {
    return yarpJNI.IVelocityControlRaw_stopRaw__SWIG_1(swigCPtr, this);
  }

}
