/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IVelocityControl {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IVelocityControl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVelocityControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_IVelocityControl(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean getAxes(SWIGTYPE_p_int axes) {
    return yarpJNI.IVelocityControl_getAxes__SWIG_0(swigCPtr, this, SWIGTYPE_p_int.getCPtr(axes));
  }

  public boolean setVelocityMode() {
    return yarpJNI.IVelocityControl_setVelocityMode(swigCPtr, this);
  }

  public boolean velocityMove(int j, double sp) {
    return yarpJNI.IVelocityControl_velocityMove__SWIG_0(swigCPtr, this, j, sp);
  }

  public boolean velocityMove(SWIGTYPE_p_double sp) {
    return yarpJNI.IVelocityControl_velocityMove__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(sp));
  }

  public boolean setRefAcceleration(int j, double acc) {
    return yarpJNI.IVelocityControl_setRefAcceleration(swigCPtr, this, j, acc);
  }

  public boolean setRefAccelerations(SWIGTYPE_p_double accs) {
    return yarpJNI.IVelocityControl_setRefAccelerations__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

  public boolean getRefAcceleration(int j, SWIGTYPE_p_double acc) {
    return yarpJNI.IVelocityControl_getRefAcceleration__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(acc));
  }

  public boolean getRefAccelerations(SWIGTYPE_p_double accs) {
    return yarpJNI.IVelocityControl_getRefAccelerations__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

  public boolean stop(int j) {
    return yarpJNI.IVelocityControl_stop__SWIG_0(swigCPtr, this, j);
  }

  public boolean stop() {
    return yarpJNI.IVelocityControl_stop__SWIG_1(swigCPtr, this);
  }

  public int getAxes() {
    return yarpJNI.IVelocityControl_getAxes__SWIG_1(swigCPtr, this);
  }

  public boolean velocityMove(DVector data) {
    return yarpJNI.IVelocityControl_velocityMove__SWIG_2(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean setRefAccelerations(DVector data) {
    return yarpJNI.IVelocityControl_setRefAccelerations__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public boolean getRefAcceleration(int j, DVector data) {
    return yarpJNI.IVelocityControl_getRefAcceleration__SWIG_1(swigCPtr, this, j, DVector.getCPtr(data), data);
  }

  public boolean getRefAccelerations(DVector data) {
    return yarpJNI.IVelocityControl_getRefAccelerations__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

}
