/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Network {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Network(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Network obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_Network(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Network() {
    this(yarpJNI.new_Network(), true);
  }

  public static boolean connect(String src, String dest, String carrier, boolean quiet) {
    return yarpJNI.Network_connect__SWIG_0(src, dest, carrier, quiet);
  }

  public static boolean connect(String src, String dest, String carrier) {
    return yarpJNI.Network_connect__SWIG_1(src, dest, carrier);
  }

  public static boolean connect(String src, String dest) {
    return yarpJNI.Network_connect__SWIG_2(src, dest);
  }

  public static boolean disconnect(String src, String dest, boolean quiet) {
    return yarpJNI.Network_disconnect__SWIG_0(src, dest, quiet);
  }

  public static boolean disconnect(String src, String dest) {
    return yarpJNI.Network_disconnect__SWIG_1(src, dest);
  }

  public static boolean isConnected(String src, String dest, boolean quiet) {
    return yarpJNI.Network_isConnected__SWIG_0(src, dest, quiet);
  }

  public static boolean isConnected(String src, String dest) {
    return yarpJNI.Network_isConnected__SWIG_1(src, dest);
  }

  public static boolean sync(String port, boolean quiet) {
    return yarpJNI.Network_sync__SWIG_0(port, quiet);
  }

  public static boolean sync(String port) {
    return yarpJNI.Network_sync__SWIG_1(port);
  }

  public static int main(int argc, SWIGTYPE_p_p_char argv) {
    return yarpJNI.Network_main(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static void init() {
    yarpJNI.Network_init();
  }

  public static void fini() {
    yarpJNI.Network_fini();
  }

  public static void assertion(boolean shouldBeTrue) {
    yarpJNI.Network_assertion(shouldBeTrue);
  }

  public static Contact queryName(String name) {
    return new Contact(yarpJNI.Network_queryName(name), true);
  }

  public static Contact registerName(String name) {
    return new Contact(yarpJNI.Network_registerName(name), true);
  }

  public static Contact registerContact(Contact contact) {
    return new Contact(yarpJNI.Network_registerContact(Contact.getCPtr(contact), contact), true);
  }

  public static Contact unregisterName(String name) {
    return new Contact(yarpJNI.Network_unregisterName(name), true);
  }

  public static Contact unregisterContact(Contact contact) {
    return new Contact(yarpJNI.Network_unregisterContact(Contact.getCPtr(contact), contact), true);
  }

  public static boolean setProperty(String name, String key, Value value) {
    return yarpJNI.Network_setProperty(name, key, Value.getCPtr(value), value);
  }

  public static Value getProperty(String name, String key) {
    long cPtr = yarpJNI.Network_getProperty(name, key);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static ConstString getNameServerName() {
    return new ConstString(yarpJNI.Network_getNameServerName(), true);
  }

  public static boolean setLocalMode(boolean flag) {
    return yarpJNI.Network_setLocalMode(flag);
  }

  public static ConstString readString(SWIGTYPE_p_bool eof) {
    return new ConstString(yarpJNI.Network_readString__SWIG_0(SWIGTYPE_p_bool.getCPtr(eof)), true);
  }

  public static ConstString readString() {
    return new ConstString(yarpJNI.Network_readString__SWIG_1(), true);
  }

  public static boolean write(Contact contact, PortWriter cmd, PortReader reply, boolean admin) {
    return yarpJNI.Network_write__SWIG_0(Contact.getCPtr(contact), contact, PortWriter.getCPtr(cmd), cmd, PortReader.getCPtr(reply), reply, admin);
  }

  public static boolean write(Contact contact, PortWriter cmd, PortReader reply) {
    return yarpJNI.Network_write__SWIG_1(Contact.getCPtr(contact), contact, PortWriter.getCPtr(cmd), cmd, PortReader.getCPtr(reply), reply);
  }

  public static boolean write(String port_name, PortWriter cmd, PortReader reply) {
    return yarpJNI.Network_write__SWIG_2(port_name, PortWriter.getCPtr(cmd), cmd, PortReader.getCPtr(reply), reply);
  }

  public static boolean checkNetwork() {
    return yarpJNI.Network_checkNetwork();
  }

}
