/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PidVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PidVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PidVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_PidVector(swigCPtr);
    }
    swigCPtr = 0;
  }

  public PidVector() {
    this(yarpJNI.new_PidVector__SWIG_0(), true);
  }

  public PidVector(long n) {
    this(yarpJNI.new_PidVector__SWIG_1(n), true);
  }

  public long size() {
    return yarpJNI.PidVector_size(swigCPtr, this);
  }

  public long capacity() {
    return yarpJNI.PidVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    yarpJNI.PidVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return yarpJNI.PidVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    yarpJNI.PidVector_clear(swigCPtr, this);
  }

  public void add(Pid x) {
    yarpJNI.PidVector_add(swigCPtr, this, Pid.getCPtr(x), x);
  }

  public Pid get(int i) {
    return new Pid(yarpJNI.PidVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Pid val) {
    yarpJNI.PidVector_set(swigCPtr, this, i, Pid.getCPtr(val), val);
  }

}
