/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PixelRgbFloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PixelRgbFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PixelRgbFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_PixelRgbFloat(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setR(float value) {
    yarpJNI.PixelRgbFloat_r_set(swigCPtr, this, value);
  }

  public float getR() {
    return yarpJNI.PixelRgbFloat_r_get(swigCPtr, this);
  }

  public void setG(float value) {
    yarpJNI.PixelRgbFloat_g_set(swigCPtr, this, value);
  }

  public float getG() {
    return yarpJNI.PixelRgbFloat_g_get(swigCPtr, this);
  }

  public void setB(float value) {
    yarpJNI.PixelRgbFloat_b_set(swigCPtr, this, value);
  }

  public float getB() {
    return yarpJNI.PixelRgbFloat_b_get(swigCPtr, this);
  }

  public PixelRgbFloat() {
    this(yarpJNI.new_PixelRgbFloat(), true);
  }

}
