/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PixelHsv {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PixelHsv(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PixelHsv obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_PixelHsv(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setH(short value) {
    yarpJNI.PixelHsv_h_set(swigCPtr, this, value);
  }

  public short getH() {
    return yarpJNI.PixelHsv_h_get(swigCPtr, this);
  }

  public void setS(short value) {
    yarpJNI.PixelHsv_s_set(swigCPtr, this, value);
  }

  public short getS() {
    return yarpJNI.PixelHsv_s_get(swigCPtr, this);
  }

  public void setV(short value) {
    yarpJNI.PixelHsv_v_set(swigCPtr, this, value);
  }

  public short getV() {
    return yarpJNI.PixelHsv_v_get(swigCPtr, this);
  }

  public PixelHsv() {
    this(yarpJNI.new_PixelHsv(), true);
  }

}
