/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PixelRgba {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PixelRgba(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PixelRgba obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_PixelRgba(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setR(short value) {
    yarpJNI.PixelRgba_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return yarpJNI.PixelRgba_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    yarpJNI.PixelRgba_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return yarpJNI.PixelRgba_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    yarpJNI.PixelRgba_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return yarpJNI.PixelRgba_b_get(swigCPtr, this);
  }

  public void setA(short value) {
    yarpJNI.PixelRgba_a_set(swigCPtr, this, value);
  }

  public short getA() {
    return yarpJNI.PixelRgba_a_get(swigCPtr, this);
  }

  public PixelRgba() {
    this(yarpJNI.new_PixelRgba__SWIG_0(), true);
  }

  public PixelRgba(short n_r, short n_g, short n_b, short n_a) {
    this(yarpJNI.new_PixelRgba__SWIG_1(n_r, n_g, n_b, n_a), true);
  }

}
