/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PortReaderCreator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PortReaderCreator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PortReaderCreator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_PortReaderCreator(swigCPtr);
    }
    swigCPtr = 0;
  }

  public PortReader create() {
    long cPtr = yarpJNI.PortReaderCreator_create(swigCPtr, this);
    return (cPtr == 0) ? null : new PortReader(cPtr, false);
  }

}
