/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PortInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PortInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PortInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_PortInfo(swigCPtr);
    }
    swigCPtr = 0;
  }

  public PortInfo() {
    this(yarpJNI.new_PortInfo(), true);
  }

  public void setTag(int value) {
    yarpJNI.PortInfo_tag_set(swigCPtr, this, value);
  }

  public int getTag() {
    return yarpJNI.PortInfo_tag_get(swigCPtr, this);
  }

  public void setIncoming(boolean value) {
    yarpJNI.PortInfo_incoming_set(swigCPtr, this, value);
  }

  public boolean getIncoming() {
    return yarpJNI.PortInfo_incoming_get(swigCPtr, this);
  }

  public void setCreated(boolean value) {
    yarpJNI.PortInfo_created_set(swigCPtr, this, value);
  }

  public boolean getCreated() {
    return yarpJNI.PortInfo_created_get(swigCPtr, this);
  }

  public void setPortName(ConstString value) {
    yarpJNI.PortInfo_portName_set(swigCPtr, this, ConstString.getCPtr(value), value);
  }

  public ConstString getPortName() {
    long cPtr = yarpJNI.PortInfo_portName_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConstString(cPtr, false);
  }

  public void setSourceName(ConstString value) {
    yarpJNI.PortInfo_sourceName_set(swigCPtr, this, ConstString.getCPtr(value), value);
  }

  public ConstString getSourceName() {
    long cPtr = yarpJNI.PortInfo_sourceName_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConstString(cPtr, false);
  }

  public void setTargetName(ConstString value) {
    yarpJNI.PortInfo_targetName_set(swigCPtr, this, ConstString.getCPtr(value), value);
  }

  public ConstString getTargetName() {
    long cPtr = yarpJNI.PortInfo_targetName_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConstString(cPtr, false);
  }

  public void setCarrierName(ConstString value) {
    yarpJNI.PortInfo_carrierName_set(swigCPtr, this, ConstString.getCPtr(value), value);
  }

  public ConstString getCarrierName() {
    long cPtr = yarpJNI.PortInfo_carrierName_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConstString(cPtr, false);
  }

  public void setMessage(ConstString value) {
    yarpJNI.PortInfo_message_set(swigCPtr, this, ConstString.getCPtr(value), value);
  }

  public ConstString getMessage() {
    long cPtr = yarpJNI.PortInfo_message_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConstString(cPtr, false);
  }

  public final static int PORTINFO_NULL = yarpJNI.PortInfo_PORTINFO_NULL_get();
  public final static int PORTINFO_CONNECTION = yarpJNI.PortInfo_PORTINFO_CONNECTION_get();
  public final static int PORTINFO_MISC = yarpJNI.PortInfo_PORTINFO_MISC_get();

}
