/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Random {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Random(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Random obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_Random(swigCPtr);
    }
    swigCPtr = 0;
  }

  public static double uniform() {
    return yarpJNI.Random_uniform__SWIG_0();
  }

  public static double normal(double m, double s) {
    return yarpJNI.Random_normal__SWIG_0(m, s);
  }

  public static void seed_c(int seed) {
    yarpJNI.Random_seed_c(seed);
  }

  public static double normal() {
    return yarpJNI.Random_normal__SWIG_1();
  }

  public static int uniform(int min, int max) {
    return yarpJNI.Random_uniform__SWIG_1(min, max);
  }

  public Random() {
    this(yarpJNI.new_Random(), true);
  }

}
