/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Searchable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Searchable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Searchable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_Searchable(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean check(String key) {
    return yarpJNI.Searchable_check__SWIG_0(swigCPtr, this, key);
  }

  public boolean check(String key, String comment) {
    return yarpJNI.Searchable_check__SWIG_1(swigCPtr, this, key, comment);
  }

  public Value find(String key) {
    return new Value(yarpJNI.Searchable_find(swigCPtr, this, key), false);
  }

  public Bottle findGroup(String key) {
    return new Bottle(yarpJNI.Searchable_findGroup__SWIG_0(swigCPtr, this, key), false);
  }

  public Bottle findGroup(String key, String comment) {
    return new Bottle(yarpJNI.Searchable_findGroup__SWIG_1(swigCPtr, this, key, comment), false);
  }

  public Value check(String key, Value fallback, String comment) {
    return new Value(yarpJNI.Searchable_check__SWIG_2(swigCPtr, this, key, Value.getCPtr(fallback), fallback, comment), true);
  }

  public Value check(String key, Value fallback) {
    return new Value(yarpJNI.Searchable_check__SWIG_3(swigCPtr, this, key, Value.getCPtr(fallback), fallback), true);
  }

  public boolean isNull() {
    return yarpJNI.Searchable_isNull(swigCPtr, this);
  }

  public ConstString toString_c() {
    return new ConstString(yarpJNI.Searchable_toString_c(swigCPtr, this), true);
  }

  public void setMonitor(SearchMonitor monitor, String context) {
    yarpJNI.Searchable_setMonitor__SWIG_0(swigCPtr, this, SearchMonitor.getCPtr(monitor), monitor, context);
  }

  public void setMonitor(SearchMonitor monitor) {
    yarpJNI.Searchable_setMonitor__SWIG_1(swigCPtr, this, SearchMonitor.getCPtr(monitor), monitor);
  }

  public SearchMonitor getMonitor() {
    long cPtr = yarpJNI.Searchable_getMonitor(swigCPtr, this);
    return (cPtr == 0) ? null : new SearchMonitor(cPtr, false);
  }

  public ConstString getContext() {
    return new ConstString(yarpJNI.Searchable_getContext(swigCPtr, this), true);
  }

  public void reportToMonitor(SearchReport report) {
    yarpJNI.Searchable_reportToMonitor(swigCPtr, this, SearchReport.getCPtr(report), report);
  }

}
