/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Time {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_Time(swigCPtr);
    }
    swigCPtr = 0;
  }

  public static void delay(double seconds) {
    yarpJNI.Time_delay(seconds);
  }

  public static double now() {
    return yarpJNI.Time_now();
  }

  public static void yield() {
    yarpJNI.Time_yield();
  }

  public static void turboBoost() {
    yarpJNI.Time_turboBoost();
  }

  public Time() {
    this(yarpJNI.new_Time(), true);
  }

}
