/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderCallbackImageRgb {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderCallbackImageRgb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderCallbackImageRgb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_TypedReaderCallbackImageRgb(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void onRead(ImageRgb datum) {
    yarpJNI.TypedReaderCallbackImageRgb_onRead__SWIG_0(swigCPtr, this, ImageRgb.getCPtr(datum), datum);
  }

  public void onRead(ImageRgb datum, TypedReaderImageRgb reader) {
    yarpJNI.TypedReaderCallbackImageRgb_onRead__SWIG_1(swigCPtr, this, ImageRgb.getCPtr(datum), datum, TypedReaderImageRgb.getCPtr(reader), reader);
  }

  public TypedReaderCallbackImageRgb() {
    this(yarpJNI.new_TypedReaderCallbackImageRgb(), true);
  }

}
