/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderImageFloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderImageFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderImageFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_TypedReaderImageFloat(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setStrict(boolean strict) {
    yarpJNI.TypedReaderImageFloat_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.TypedReaderImageFloat_setStrict__SWIG_1(swigCPtr, this);
  }

  public ImageFloat read(boolean shouldWait) {
    long cPtr = yarpJNI.TypedReaderImageFloat_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new ImageFloat(cPtr, false);
  }

  public ImageFloat read() {
    long cPtr = yarpJNI.TypedReaderImageFloat_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageFloat(cPtr, false);
  }

  public ImageFloat lastRead() {
    long cPtr = yarpJNI.TypedReaderImageFloat_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageFloat(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.TypedReaderImageFloat_isClosed(swigCPtr, this);
  }

  public void useCallback(TypedReaderCallbackImageFloat callback) {
    yarpJNI.TypedReaderImageFloat_useCallback(swigCPtr, this, TypedReaderCallbackImageFloat.getCPtr(callback), callback);
  }

  public int getPendingReads() {
    return yarpJNI.TypedReaderImageFloat_getPendingReads(swigCPtr, this);
  }

  public ConstString getName() {
    return new ConstString(yarpJNI.TypedReaderImageFloat_getName(swigCPtr, this), true);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.TypedReaderImageFloat_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.TypedReaderImageFloat_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.TypedReaderImageFloat_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

}
