/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderCallbackBottle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderCallbackBottle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderCallbackBottle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_TypedReaderCallbackBottle(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void onRead(Bottle datum) {
    yarpJNI.TypedReaderCallbackBottle_onRead__SWIG_0(swigCPtr, this, Bottle.getCPtr(datum), datum);
  }

  public void onRead(Bottle datum, TypedReaderBottle reader) {
    yarpJNI.TypedReaderCallbackBottle_onRead__SWIG_1(swigCPtr, this, Bottle.getCPtr(datum), datum, TypedReaderBottle.getCPtr(reader), reader);
  }

  public TypedReaderCallbackBottle() {
    this(yarpJNI.new_TypedReaderCallbackBottle(), true);
  }

}
