/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderProperty {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderProperty(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_TypedReaderProperty(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setStrict(boolean strict) {
    yarpJNI.TypedReaderProperty_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.TypedReaderProperty_setStrict__SWIG_1(swigCPtr, this);
  }

  public Property read(boolean shouldWait) {
    long cPtr = yarpJNI.TypedReaderProperty_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public Property read() {
    long cPtr = yarpJNI.TypedReaderProperty_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public Property lastRead() {
    long cPtr = yarpJNI.TypedReaderProperty_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.TypedReaderProperty_isClosed(swigCPtr, this);
  }

  public void useCallback(TypedReaderCallbackProperty callback) {
    yarpJNI.TypedReaderProperty_useCallback(swigCPtr, this, TypedReaderCallbackProperty.getCPtr(callback), callback);
  }

  public int getPendingReads() {
    return yarpJNI.TypedReaderProperty_getPendingReads(swigCPtr, this);
  }

  public ConstString getName() {
    return new ConstString(yarpJNI.TypedReaderProperty_getName(swigCPtr, this), true);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.TypedReaderProperty_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.TypedReaderProperty_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.TypedReaderProperty_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

}
