/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderBottle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderBottle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderBottle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_TypedReaderBottle(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setStrict(boolean strict) {
    yarpJNI.TypedReaderBottle_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.TypedReaderBottle_setStrict__SWIG_1(swigCPtr, this);
  }

  public Bottle read(boolean shouldWait) {
    long cPtr = yarpJNI.TypedReaderBottle_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new Bottle(cPtr, false);
  }

  public Bottle read() {
    long cPtr = yarpJNI.TypedReaderBottle_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Bottle(cPtr, false);
  }

  public Bottle lastRead() {
    long cPtr = yarpJNI.TypedReaderBottle_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new Bottle(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.TypedReaderBottle_isClosed(swigCPtr, this);
  }

  public void useCallback(BottleCallback callback) {
    yarpJNI.TypedReaderBottle_useCallback(swigCPtr, this, BottleCallback.getCPtr(callback), callback);
  }

  public int getPendingReads() {
    return yarpJNI.TypedReaderBottle_getPendingReads(swigCPtr, this);
  }

  public ConstString getName() {
    return new ConstString(yarpJNI.TypedReaderBottle_getName(swigCPtr, this), true);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.TypedReaderBottle_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.TypedReaderBottle_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.TypedReaderBottle_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

}
