/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class TypedReaderCallbackImageFloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypedReaderCallbackImageFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypedReaderCallbackImageFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_TypedReaderCallbackImageFloat(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void onRead(ImageFloat datum) {
    yarpJNI.TypedReaderCallbackImageFloat_onRead__SWIG_0(swigCPtr, this, ImageFloat.getCPtr(datum), datum);
  }

  public void onRead(ImageFloat datum, TypedReaderImageFloat reader) {
    yarpJNI.TypedReaderCallbackImageFloat_onRead__SWIG_1(swigCPtr, this, ImageFloat.getCPtr(datum), datum, TypedReaderImageFloat.getCPtr(reader), reader);
  }

  public TypedReaderCallbackImageFloat() {
    this(yarpJNI.new_TypedReaderCallbackImageFloat(), true);
  }

}
