/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Value extends Portable {
  private long swigCPtr;

  protected Value(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.SWIGValueUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Value obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yarpJNI.delete_Value(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Value() {
    this(yarpJNI.new_Value__SWIG_0(), true);
  }

  public Value(int x, boolean isVocab) {
    this(yarpJNI.new_Value__SWIG_1(x, isVocab), true);
  }

  public Value(int x) {
    this(yarpJNI.new_Value__SWIG_2(x), true);
  }

  public Value(double x) {
    this(yarpJNI.new_Value__SWIG_3(x), true);
  }

  public Value(String str, boolean isVocab) {
    this(yarpJNI.new_Value__SWIG_4(str, isVocab), true);
  }

  public Value(String str) {
    this(yarpJNI.new_Value__SWIG_5(str), true);
  }

  public Value(SWIGTYPE_p_void data, int length) {
    this(yarpJNI.new_Value__SWIG_6(SWIGTYPE_p_void.getCPtr(data), length), true);
  }

  public Value(Value alt) {
    this(yarpJNI.new_Value__SWIG_7(Value.getCPtr(alt), alt), true);
  }

  public boolean isInt() {
    return yarpJNI.Value_isInt(swigCPtr, this);
  }

  public boolean isString() {
    return yarpJNI.Value_isString(swigCPtr, this);
  }

  public boolean isDouble() {
    return yarpJNI.Value_isDouble(swigCPtr, this);
  }

  public boolean isList() {
    return yarpJNI.Value_isList(swigCPtr, this);
  }

  public boolean isVocab() {
    return yarpJNI.Value_isVocab(swigCPtr, this);
  }

  public boolean isBlob() {
    return yarpJNI.Value_isBlob(swigCPtr, this);
  }

  public int asInt() {
    return yarpJNI.Value_asInt(swigCPtr, this);
  }

  public int asVocab() {
    return yarpJNI.Value_asVocab(swigCPtr, this);
  }

  public double asDouble() {
    return yarpJNI.Value_asDouble(swigCPtr, this);
  }

  public ConstString asString() {
    return new ConstString(yarpJNI.Value_asString(swigCPtr, this), true);
  }

  public Bottle asList() {
    long cPtr = yarpJNI.Value_asList(swigCPtr, this);
    return (cPtr == 0) ? null : new Bottle(cPtr, false);
  }

  public String asBlob() {
    return yarpJNI.Value_asBlob(swigCPtr, this);
  }

  public int asBlobLength() {
    return yarpJNI.Value_asBlobLength(swigCPtr, this);
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.Value_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

  public boolean check(String key) {
    return yarpJNI.Value_check(swigCPtr, this, key);
  }

  public Value find(String key) {
    return new Value(yarpJNI.Value_find(swigCPtr, this, key), false);
  }

  public Bottle findGroup(String key) {
    return new Bottle(yarpJNI.Value_findGroup(swigCPtr, this, key), false);
  }

  public boolean isEqual(Value alt) {
    return yarpJNI.Value_isEqual(swigCPtr, this, Value.getCPtr(alt), alt);
  }

  public boolean notEqual(Value alt) {
    return yarpJNI.Value_notEqual(swigCPtr, this, Value.getCPtr(alt), alt);
  }

  public void fromString(String str) {
    yarpJNI.Value_fromString(swigCPtr, this, str);
  }

  public ConstString toString_c() {
    return new ConstString(yarpJNI.Value_toString_c(swigCPtr, this), true);
  }

  public Value create() {
    long cPtr = yarpJNI.Value_create(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value clone_c() {
    long cPtr = yarpJNI.Value_clone_c(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public int getCode() {
    return yarpJNI.Value_getCode(swigCPtr, this);
  }

  public static Value makeInt(int x) {
    long cPtr = yarpJNI.Value_makeInt(x);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeDouble(double x) {
    long cPtr = yarpJNI.Value_makeDouble(x);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeString(String str) {
    long cPtr = yarpJNI.Value_makeString(str);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeVocab(int v) {
    long cPtr = yarpJNI.Value_makeVocab__SWIG_0(v);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeVocab(String str) {
    long cPtr = yarpJNI.Value_makeVocab__SWIG_1(str);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeBlob(SWIGTYPE_p_void data, int length) {
    long cPtr = yarpJNI.Value_makeBlob(SWIGTYPE_p_void.getCPtr(data), length);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeList() {
    long cPtr = yarpJNI.Value_makeList__SWIG_0();
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeList(String txt) {
    long cPtr = yarpJNI.Value_makeList__SWIG_1(txt);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value makeValue(String txt) {
    long cPtr = yarpJNI.Value_makeValue(txt);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static Value getNullValue() {
    return new Value(yarpJNI.Value_getNullValue(), false);
  }

  public String toString() {
    return yarpJNI.Value_toString(swigCPtr, this);
  }

}
