/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public interface yarpConstants {
  public final static int BOTTLE_TAG_INT = yarpJNI.BOTTLE_TAG_INT_get();
  public final static int BOTTLE_TAG_VOCAB = yarpJNI.BOTTLE_TAG_VOCAB_get();
  public final static int BOTTLE_TAG_DOUBLE = yarpJNI.BOTTLE_TAG_DOUBLE_get();
  public final static int BOTTLE_TAG_STRING = yarpJNI.BOTTLE_TAG_STRING_get();
  public final static int BOTTLE_TAG_BLOB = yarpJNI.BOTTLE_TAG_BLOB_get();
  public final static int BOTTLE_TAG_LIST = yarpJNI.BOTTLE_TAG_LIST_get();
  public final static int VOCAB_CALIBRATE_JOINT = yarpJNI.VOCAB_CALIBRATE_JOINT_get();
  public final static int VOCAB_CALIBRATE = yarpJNI.VOCAB_CALIBRATE_get();
  public final static int VOCAB_ABORTCALIB = yarpJNI.VOCAB_ABORTCALIB_get();
  public final static int VOCAB_ABORTPARK = yarpJNI.VOCAB_ABORTPARK_get();
  public final static int VOCAB_CALIBRATE_DONE = yarpJNI.VOCAB_CALIBRATE_DONE_get();
  public final static int VOCAB_PARK = yarpJNI.VOCAB_PARK_get();
  public final static int VOCAB_SET = yarpJNI.VOCAB_SET_get();
  public final static int VOCAB_GET = yarpJNI.VOCAB_GET_get();
  public final static int VOCAB_IS = yarpJNI.VOCAB_IS_get();
  public final static int VOCAB_FAILED = yarpJNI.VOCAB_FAILED_get();
  public final static int VOCAB_OK = yarpJNI.VOCAB_OK_get();
  public final static int VOCAB_OFFSET = yarpJNI.VOCAB_OFFSET_get();
  public final static int VOCAB_PID = yarpJNI.VOCAB_PID_get();
  public final static int VOCAB_PIDS = yarpJNI.VOCAB_PIDS_get();
  public final static int VOCAB_REF = yarpJNI.VOCAB_REF_get();
  public final static int VOCAB_REFS = yarpJNI.VOCAB_REFS_get();
  public final static int VOCAB_LIM = yarpJNI.VOCAB_LIM_get();
  public final static int VOCAB_LIMS = yarpJNI.VOCAB_LIMS_get();
  public final static int VOCAB_RESET = yarpJNI.VOCAB_RESET_get();
  public final static int VOCAB_DISABLE = yarpJNI.VOCAB_DISABLE_get();
  public final static int VOCAB_ENABLE = yarpJNI.VOCAB_ENABLE_get();
  public final static int VOCAB_ERR = yarpJNI.VOCAB_ERR_get();
  public final static int VOCAB_ERRS = yarpJNI.VOCAB_ERRS_get();
  public final static int VOCAB_OUTPUT = yarpJNI.VOCAB_OUTPUT_get();
  public final static int VOCAB_OUTPUTS = yarpJNI.VOCAB_OUTPUTS_get();
  public final static int VOCAB_REFERENCE = yarpJNI.VOCAB_REFERENCE_get();
  public final static int VOCAB_REFERENCES = yarpJNI.VOCAB_REFERENCES_get();
  public final static int VOCAB_AXES = yarpJNI.VOCAB_AXES_get();
  public final static int VOCAB_MOTION_DONE = yarpJNI.VOCAB_MOTION_DONE_get();
  public final static int VOCAB_MOTION_DONES = yarpJNI.VOCAB_MOTION_DONES_get();
  public final static int VOCAB_POSITION_MODE = yarpJNI.VOCAB_POSITION_MODE_get();
  public final static int VOCAB_POSITION_MOVE = yarpJNI.VOCAB_POSITION_MOVE_get();
  public final static int VOCAB_POSITION_MOVES = yarpJNI.VOCAB_POSITION_MOVES_get();
  public final static int VOCAB_RELATIVE_MOVE = yarpJNI.VOCAB_RELATIVE_MOVE_get();
  public final static int VOCAB_RELATIVE_MOVES = yarpJNI.VOCAB_RELATIVE_MOVES_get();
  public final static int VOCAB_REF_SPEED = yarpJNI.VOCAB_REF_SPEED_get();
  public final static int VOCAB_REF_SPEEDS = yarpJNI.VOCAB_REF_SPEEDS_get();
  public final static int VOCAB_REF_ACCELERATION = yarpJNI.VOCAB_REF_ACCELERATION_get();
  public final static int VOCAB_REF_ACCELERATIONS = yarpJNI.VOCAB_REF_ACCELERATIONS_get();
  public final static int VOCAB_STOP = yarpJNI.VOCAB_STOP_get();
  public final static int VOCAB_STOPS = yarpJNI.VOCAB_STOPS_get();
  public final static int VOCAB_VELOCITY_MODE = yarpJNI.VOCAB_VELOCITY_MODE_get();
  public final static int VOCAB_VELOCITY_MOVE = yarpJNI.VOCAB_VELOCITY_MOVE_get();
  public final static int VOCAB_VELOCITY_MOVES = yarpJNI.VOCAB_VELOCITY_MOVES_get();
  public final static int VOCAB_E_RESET = yarpJNI.VOCAB_E_RESET_get();
  public final static int VOCAB_E_RESETS = yarpJNI.VOCAB_E_RESETS_get();
  public final static int VOCAB_ENCODER = yarpJNI.VOCAB_ENCODER_get();
  public final static int VOCAB_ENCODERS = yarpJNI.VOCAB_ENCODERS_get();
  public final static int VOCAB_ENCODER_SPEED = yarpJNI.VOCAB_ENCODER_SPEED_get();
  public final static int VOCAB_ENCODER_SPEEDS = yarpJNI.VOCAB_ENCODER_SPEEDS_get();
  public final static int VOCAB_ENCODER_ACCELERATION = yarpJNI.VOCAB_ENCODER_ACCELERATION_get();
  public final static int VOCAB_ENCODER_ACCELERATIONS = yarpJNI.VOCAB_ENCODER_ACCELERATIONS_get();
  public final static int VOCAB_AMP_ENABLE = yarpJNI.VOCAB_AMP_ENABLE_get();
  public final static int VOCAB_AMP_DISABLE = yarpJNI.VOCAB_AMP_DISABLE_get();
  public final static int VOCAB_AMP_CURRENT = yarpJNI.VOCAB_AMP_CURRENT_get();
  public final static int VOCAB_AMP_CURRENTS = yarpJNI.VOCAB_AMP_CURRENTS_get();
  public final static int VOCAB_AMP_MAXCURRENT = yarpJNI.VOCAB_AMP_MAXCURRENT_get();
  public final static int VOCAB_AMP_STATUS = yarpJNI.VOCAB_AMP_STATUS_get();
  public final static int VOCAB_LIMITS = yarpJNI.VOCAB_LIMITS_get();
  public final static int VOCAB_INFO_NAME = yarpJNI.VOCAB_INFO_NAME_get();
}
