/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public final class YarpVocabPixelTypesEnum {
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_INVALID = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_INVALID", yarpJNI.VOCAB_PIXEL_INVALID_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_MONO = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_MONO", yarpJNI.VOCAB_PIXEL_MONO_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_MONO16 = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_MONO16", yarpJNI.VOCAB_PIXEL_MONO16_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_RGB = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_RGB", yarpJNI.VOCAB_PIXEL_RGB_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_RGBA = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_RGBA", yarpJNI.VOCAB_PIXEL_RGBA_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_BGRA = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_BGRA", yarpJNI.VOCAB_PIXEL_BGRA_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_INT = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_INT", yarpJNI.VOCAB_PIXEL_INT_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_HSV = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_HSV", yarpJNI.VOCAB_PIXEL_HSV_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_BGR = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_BGR", yarpJNI.VOCAB_PIXEL_BGR_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_MONO_SIGNED = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_MONO_SIGNED", yarpJNI.VOCAB_PIXEL_MONO_SIGNED_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_RGB_SIGNED = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_RGB_SIGNED", yarpJNI.VOCAB_PIXEL_RGB_SIGNED_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_RGB_INT = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_RGB_INT", yarpJNI.VOCAB_PIXEL_RGB_INT_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_MONO_FLOAT = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_MONO_FLOAT", yarpJNI.VOCAB_PIXEL_MONO_FLOAT_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_RGB_FLOAT = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_RGB_FLOAT", yarpJNI.VOCAB_PIXEL_RGB_FLOAT_get());
  public final static YarpVocabPixelTypesEnum VOCAB_PIXEL_HSV_FLOAT = new YarpVocabPixelTypesEnum("VOCAB_PIXEL_HSV_FLOAT", yarpJNI.VOCAB_PIXEL_HSV_FLOAT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static YarpVocabPixelTypesEnum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + YarpVocabPixelTypesEnum.class + " with value " + swigValue);
  }

  private YarpVocabPixelTypesEnum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private YarpVocabPixelTypesEnum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private YarpVocabPixelTypesEnum(String swigName, YarpVocabPixelTypesEnum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static YarpVocabPixelTypesEnum[] swigValues = { VOCAB_PIXEL_INVALID, VOCAB_PIXEL_MONO, VOCAB_PIXEL_MONO16, VOCAB_PIXEL_RGB, VOCAB_PIXEL_RGBA, VOCAB_PIXEL_BGRA, VOCAB_PIXEL_INT, VOCAB_PIXEL_HSV, VOCAB_PIXEL_BGR, VOCAB_PIXEL_MONO_SIGNED, VOCAB_PIXEL_RGB_SIGNED, VOCAB_PIXEL_RGB_INT, VOCAB_PIXEL_MONO_FLOAT, VOCAB_PIXEL_RGB_FLOAT, VOCAB_PIXEL_HSV_FLOAT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

